version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.10-rc-management-alpine
    container_name: 'rabbitmq'
    restart: 'always'
    environment:
      - "RABBITMQ_DEFAULT_USER=docker"
      - "RABBITMQ_DEFAULT_PASS=dockerpassword"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq_hello_world

networks:
  rabbitmq_hello_world:
    driver: bridge